from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];site=ROOT/'site'
idx=(site/'index.html').read_text(encoding='utf-8');css=(site/'v21-core-ui.css').read_text(encoding='utf-8');run=(site/'v21-runtime.js').read_text(encoding='utf-8');app=(site/'app.js').read_text(encoding='utf-8');plat=(site/'v16-platform.js').read_text(encoding='utf-8');exam=(site/'v16-exam.js').read_text(encoding='utf-8');sw=(site/'sw.js').read_text(encoding='utf-8');meta=(site/'release-meta.js').read_text(encoding='utf-8');ver=json.loads((ROOT/'VERSION.json').read_text(encoding='utf-8'))
assert ('data-docnr-release="v21-0-major-stability-unified-runtime"' in idx) or ('data-docnr-release="v21-1-mobile-essentials-reliable-back"' in idx) or (('data-docnr-release="v21-2-cross-device-stable"' in idx) or (('data-docnr-release="v21-3-no-sidebar-stable"' in idx or 'data-docnr-release="v21-4-completion-stable"' in idx or 'data-docnr-release="v22-0-production-recovery"' in idx)))
assert (('v21-core-ui.css?v=20260924-v21-0' in idx) or ('v21-core-ui.css?v=20260925-v21-1' in idx) or (('v21-core-ui.css?v=20260925-v21-2' in idx) or ('v21-core-ui.css?v=20260925-v21-3' in idx) or ('v21-core-ui.css?v=20260929-v22-0' in idx))) and idx.index('v21-core-ui.css')>idx.index('v19-programming-activity.css')
assert ((ver['version'],ver['release_marker']) in {('21.0','V21.0'),('21.1','V21.1'),('21.2','V21.2'),('21.3','V21.3'),('21.4','V21.4'),('22.0','V22.0')} and f'RELEASE_VERSION="{ver["release_marker"]}"' in meta)
for t in ['const isTeacher=', 'TEACHER_ROUTES', 'workadmin","ตรวจงานและคะแนน', 'attendancehub","เช็คชื่อ']: assert t in app,t
for t in ['my_teacher_assignments_v206','staff_submission_queue_v206','staff_submission_detail_v206','staff_grade_submission_v206','staff_subject_gradebook_v206','staff_room_groups_v206','staff_room_group_user_ids_v206','staff_attendance_sessions_v206','staff_issue_late_attendance_barcode_v206','staff_revoke_late_attendance_barcode_v206','admin_room_groups_v206','admin_replace_room_group_members_v206','admin_auto_number_room_group_v206','admin_bind_room_group_subject_v206','admin_sync_room_group_v206','admin_link_room_group_classroom_v206','JsBarcode']: assert t in plat,t
for t in ['staff_exam_dashboard_v206','staff_create_exam_preset_v206','staff_publish_exam_v206','staff_exam_attempts_v206','staff_grade_exam_attempt_v206','staff_reset_exam_user_v206','staff_delete_exam_v206','p.role==="teacher"']: assert t in exam,t
for t in ['.docnr-route-loading','.docnr-skeleton-page','#docnr-mobile-nav','.docnr-filterbar','@media (max-width:620px)']: assert t in css,t
assert ("const RELEASE='V22.0'" in (ROOT/'site/v22-runtime.js').read_text(encoding='utf-8') or "const RELEASE='V21.4'" in run) and "$$('.docnr-route-loading').forEach(x=>x.remove())" in run
assert ('doc-full-nr-v21-0-major-stability-unified-runtime-20260924' in sw) or ('doc-full-nr-v21-1-mobile-essentials-reliable-back-20260925' in sw) or (('doc-full-nr-v21-2-cross-device-stable-20260925' in sw) or (('doc-full-nr-v21-3-no-sidebar-stable-20260925' in sw or 'doc-full-nr-v21-4-completion-stable-20260929' in sw or 'doc-full-nr-v22-0-production-recovery-20260929' in sw)))
print('V20.7 LONG-TERM UX + TEACHER WORKSPACE COMPATIBILITY PASS VIA V21')
