import {FormEvent,useEffect,useState} from 'react';
import {api} from '../services/api';
import {Modal} from '../components/Modal';
import {ErrorPanel} from '../components/ErrorPanel';
import {fmtDate} from '../lib/utils';
export function ExamsPage(){
 const[data,setData]=useState<{subjects:any[];exams:any[]}>({subjects:[],exams:[]});const[err,setErr]=useState('');const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[attempts,setAttempts]=useState<any[]|null>(null);const[current,setCurrent]=useState<any|null>(null);
 async function load(){setErr('');try{const d=await api.examDashboard();setData({subjects:d.subjects||[],exams:d.exams||[]})}catch(e:any){setErr(e.message||String(e))}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');try{const f=new FormData(e.currentTarget);await api.rpc('staff_create_exam_preset_v206',{p_subject_id:String(f.get('subject_id')),p_exam_kind:String(f.get('exam_kind')),p_title:String(f.get('title')),p_open_at:f.get('open_at')?new Date(String(f.get('open_at'))).toISOString():null,p_due_at:f.get('due_at')?new Date(String(f.get('due_at'))).toISOString():null});setOpen(false);await load()}catch(e:any){setErr(e.message||String(e))}finally{setBusy(false)}}
 async function publish(x:any){try{await api.rpc('staff_publish_exam_v206',{p_exam_id:x.id,p_open_at:x.open_at||new Date().toISOString(),p_due_at:x.due_at||null});await load()}catch(e:any){setErr(e.message||String(e))}}
 async function remove(x:any){if(!confirm(`ลบข้อสอบ “${x.title}” ?`))return;try{await api.rpc('staff_delete_exam_v206',{p_exam_id:x.id});await load()}catch(e:any){setErr(e.message||String(e))}}
 async function showAttempts(x:any){setCurrent(x);setAttempts(null);try{setAttempts(await api.rpc<any[]>('staff_exam_attempts_v206',{p_exam_id:x.id}))}catch(e:any){setErr(e.message||String(e))}}
 return <><div className="page-head"><div><div className="eyebrow">EXAM SYSTEM</div><h1>ข้อสอบ</h1><p>สร้างจากคลังข้อสอบ ติดตามสถานะ และดูผู้เข้าสอบ</p></div><button className="btn primary" onClick={()=>setOpen(true)}>+ สร้างข้อสอบ</button></div>{err&&<ErrorPanel message={err} onRetry={()=>void load()}/>}<div className="data-card"><table><thead><tr><th>ข้อสอบ</th><th>วิชา</th><th>ชนิด</th><th>สถานะ</th><th>ช่วงเวลา</th><th>ผู้เข้าสอบ</th><th>จัดการ</th></tr></thead><tbody>{data.exams.map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.question_count_target||0} ข้อ • {x.full_score||0} คะแนน</small></td><td>{x.subject_code} {x.subject_name}</td><td>{x.exam_kind||'-'}</td><td><span className={'status-chip '+(x.status==='published'?'ok':'')}>{x.status}</span></td><td><small>{fmtDate(x.open_at)}</small><small>ถึง {fmtDate(x.due_at)}</small></td><td>{x.attempt_count||0}</td><td><div className="row"><button className="btn tiny" onClick={()=>void showAttempts(x)}>Attempts</button>{x.status!=='published'&&<button className="btn tiny success" onClick={()=>void publish(x)}>Publish</button>}<button className="btn tiny danger" onClick={()=>void remove(x)}>ลบ</button></div></td></tr>)}</tbody></table></div>{open&&<Modal title="สร้างข้อสอบจากคลัง" onClose={()=>setOpen(false)}><form onSubmit={create}><div className="form-grid"><label>รายวิชา<select name="subject_id" required><option value="">เลือกรายวิชา</option>{data.subjects.map(s=><option value={s.id} key={s.id}>{s.code} {s.name} ({s.bank_count||0} ข้อ)</option>)}</select></label><label>ประเภท<select name="exam_kind"><option value="midterm">กลางภาค</option><option value="final">ปลายภาค</option><option value="quiz">Quiz</option></select></label><label className="span2">ชื่อข้อสอบ<input name="title" required/></label><label>เปิดสอบ<input name="open_at" type="datetime-local"/></label><label>ปิดสอบ<input name="due_at" type="datetime-local"/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>{busy?'กำลังสร้าง...':'สร้างข้อสอบ'}</button></div></form></Modal>}{current&&<Modal title={`ผู้เข้าสอบ: ${current.title}`} onClose={()=>{setCurrent(null);setAttempts(null)}}>{attempts===null?<div className="empty">กำลังโหลด...</div>:<div className="data-card compact"><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>ครั้ง</th><th>สถานะ</th><th>คะแนน</th><th>เหตุผิดปกติ</th></tr></thead><tbody>{attempts.map(a=><tr key={a.id}><td>{a.student_code||'-'}</td><td><b>{a.full_name}</b></td><td>{a.attempt_no}</td><td>{a.status}</td><td>{a.score??'-'}/{a.max_score??'-'}</td><td>{a.violation_count||0}</td></tr>)}</tbody></table></div>}</Modal>}</>
}
