import {FormEvent,useEffect,useState} from 'react';
import {api} from '../services/api';
import {Modal} from '../components/Modal';
import {ErrorPanel} from '../components/ErrorPanel';
import {fmtDate} from '../lib/utils';
export function GradingPage(){
 const[items,setItems]=useState<any[]>([]);const[detail,setDetail]=useState<any|null>(null);const[err,setErr]=useState('');const[busy,setBusy]=useState(false);
 async function load(){setErr('');try{setItems(await api.submissionQueue())}catch(e:any){setErr(e.message||String(e))}}
 useEffect(()=>{void load()},[]);
 async function open(id:string){setErr('');try{setDetail(await api.rpc('staff_submission_detail_v206',{p_submission_id:id}))}catch(e:any){setErr(e.message||String(e))}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;setBusy(true);try{const f=new FormData(e.currentTarget);await api.rpc('staff_grade_submission_v206',{p_submission_id:detail.submission.id,p_score:Number(f.get('score')),p_max_score:Number(f.get('max_score')),p_grade:String(f.get('grade')||''),p_admin_comment:String(f.get('comment')||''),p_rubric_result:{},p_reason:'graded_from_v23_console',p_request_key:crypto.randomUUID()});setDetail(null);await load()}catch(e:any){setErr(e.message||String(e))}finally{setBusy(false)}}
 return <><div className="page-head"><div><div className="eyebrow">GRADING QUEUE</div><h1>ตรวจงาน</h1><p>คิวงานมาจาก RPC ที่จำกัดสิทธิ์ตามวิชาที่สอน</p></div><span className="status-chip">{items.filter(x=>x.status!=='graded').length} งานรอตรวจ</span></div>{err&&<ErrorPanel message={err} onRetry={()=>void load()}/>}<div className="data-card"><table><thead><tr><th>ผู้เรียน</th><th>ใบงาน</th><th>วิชา</th><th>สถานะ</th><th>ส่งเมื่อ</th><th>คะแนน</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.full_name}</b><small>{x.student_code} • {x.class_name||x.room_label||'-'}</small></td><td>{x.worksheet_title}</td><td>{x.subject_code} {x.subject_name}</td><td><span className={'status-chip '+(x.status==='graded'?'ok':'warn')}>{x.status}</span></td><td>{fmtDate(x.submitted_at)}</td><td>{x.score??'-'}/{x.max_score??'-'}</td><td><button className="btn small primary" onClick={()=>void open(x.id)}>เปิดตรวจ</button></td></tr>)}</tbody></table></div>{detail&&<Modal title={`ตรวจงาน: ${detail.student?.full_name||''}`} onClose={()=>setDetail(null)}><div className="review-grid"><section><h4>{detail.worksheet?.title}</h4>{Object.entries(detail.submission?.answers||{}).map(([k,v])=><div className="answer-card" key={k}><b>{k}</b><div>คำตอบ: {String(v??'')}</div><small>เฉลย: {String(detail.answer_key?.answer_key?.[k]??'-')}</small></div>)}</section><form className="grade-form" onSubmit={save}><label>คะแนน<input name="score" type="number" step="0.01" defaultValue={detail.grade?.score??''} required/></label><label>คะแนนเต็ม<input name="max_score" type="number" step="0.01" defaultValue={detail.grade?.max_score??100} required/></label><label>เกรด<input name="grade" defaultValue={detail.grade?.grade??''}/></label><label>ความคิดเห็น<textarea name="comment" defaultValue={detail.grade?.admin_comment??''}/></label><button className="btn success wide" disabled={busy}>{busy?'กำลังบันทึก...':'บันทึกผลตรวจ'}</button></form></div></Modal>}</>
}
