import {FormEvent,useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {Modal} from '../components/Modal';
import {ErrorPanel} from '../components/ErrorPanel';

export function RoomGroupsPage(){
  const[groups,setGroups]=useState<any[]>([]);const[users,setUsers]=useState<any[]>([]);const[subjects,setSubjects]=useState<any[]>([]);const[err,setErr]=useState('');
  const[editor,setEditor]=useState<any|null>(null);const[selected,setSelected]=useState<string[]>([]);const[subjectId,setSubjectId]=useState('');const[busy,setBusy]=useState(false);
  async function load(){setErr('');try{const[g,u,s]=await Promise.all([api.roomGroups(),api.users(),api.subjects()]);setGroups(g||[]);setUsers(u.filter(x=>x.role==='user'&&x.active));setSubjects(s)}catch(e:any){setErr(e.message||String(e))}}
  useEffect(()=>{void load()},[]);
  async function openGroup(g?:any){setErr('');if(!g){setEditor({id:null,code:'',name:'',academic_year:'2569',semester:'1',level:'',department:'',major:'',description:'',active:true});setSelected([]);setSubjectId('');return}setEditor(g);setSubjectId('');try{const m=await api.rpc<any[]>('admin_room_group_members_v205',{p_group_id:g.id});setSelected((m||[]).filter(x=>x.active).map(x=>x.user_id))}catch(e:any){setErr(e.message||String(e))}}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;setBusy(true);setErr('');try{const f=new FormData(e.currentTarget);const r:any=await api.rpc('admin_upsert_room_group_v205',{p_group_id:editor.id||null,p_code:String(f.get('code')||''),p_name:String(f.get('name')||''),p_academic_year:String(f.get('academic_year')||''),p_semester:String(f.get('semester')||''),p_level:String(f.get('level')||''),p_department:String(f.get('department')||''),p_major:String(f.get('major')||''),p_description:String(f.get('description')||''),p_active:true});const gid=editor.id||r?.id;if(!gid)throw new Error('ไม่พบ group id หลังบันทึก');const members=selected.map((id,i)=>({user_id:id,seat_number:i+1}));await api.rpc('admin_replace_room_group_members_v206',{p_group_id:gid,p_members:members});if(subjectId)await api.rpc('admin_bind_room_group_subject_v206',{p_group_id:gid,p_subject_id:subjectId,p_active:true});await api.rpc('admin_auto_number_room_group_v206',{p_group_id:gid});await api.rpc('admin_sync_room_group_v206',{p_group_id:gid});setEditor(null);await load()}catch(e:any){setErr(e.message||String(e))}finally{setBusy(false)}}
  const selectedSet=useMemo(()=>new Set(selected),[selected]);
  return <><div className="page-head"><div><div className="eyebrow">ADMIN WORKSPACE</div><h1>กลุ่มห้อง</h1><p>สร้างกลุ่มห้อง จัดสมาชิก ผูกรายวิชา และ sync เข้าห้องเรียนจริง</p></div><button className="btn primary" onClick={()=>void openGroup()}>+ สร้างกลุ่มห้อง</button></div>{err&&<ErrorPanel message={err} onRetry={()=>void load()}/>}<div className="card-grid">{groups.map(g=><article className="panel" key={g.id}><div className="row-between"><span className="code-pill">{g.code}</span><span className="status-chip ok">{g.active?'ACTIVE':'OFF'}</span></div><h3>{g.name}</h3><p>{g.classroom_name||'ยังไม่ sync ห้องเรียน'}</p><div className="mini-stats"><span>สมาชิก <b>{g.member_count||0}</b></span><span>วิชา <b>{g.bound_subject_count||0}</b></span></div><button className="btn" onClick={()=>void openGroup(g)}>จัดการกลุ่ม</button></article>)}</div>{!groups.length&&!err&&<div className="empty panel">ยังไม่มีกลุ่มห้อง</div>}{editor&&<Modal title={editor.id?'จัดการกลุ่มห้อง':'สร้างกลุ่มห้อง'} onClose={()=>setEditor(null)}><form onSubmit={save}><div className="form-grid"><label>รหัสกลุ่ม<input name="code" defaultValue={editor.code||''} placeholder="เช่น CP-1A"/></label><label>ชื่อกลุ่ม<input name="name" defaultValue={editor.name||''} required/></label><label>ปีการศึกษา<input name="academic_year" defaultValue={editor.academic_year||''}/></label><label>ภาคเรียน<input name="semester" defaultValue={editor.semester||''}/></label><label>ระดับ<input name="level" defaultValue={editor.level||''}/></label><label>แผนก<input name="department" defaultValue={editor.department||''}/></label><label>สาขา<input name="major" defaultValue={editor.major||''}/></label><label>ผูกรายวิชา<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">ยังไม่ผูกเพิ่ม</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} {s.name}</option>)}</select></label><label className="span2">คำอธิบาย<textarea name="description" defaultValue={editor.description||''}/></label></div><div className="member-picker"><h4>สมาชิก ({selected.length})</h4><div className="member-grid">{users.map(u=><label className="check-card" key={u.id}><input type="checkbox" checked={selectedSet.has(u.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,u.id]:v.filter(x=>x!==u.id))}/><span><b>{u.full_name||u.username||'-'}</b><small>{u.student_code||'-'} • {u.class_name||'-'}</small></span></label>)}</div></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setEditor(null)}>ยกเลิก</button><button className="btn primary" disabled={busy}>{busy?'กำลัง Sync...':'บันทึก + Sync'}</button></div></form></Modal>}</>
}
