import {useEffect,useState} from 'react';
import {api} from '../services/api';
import {ErrorPanel} from '../components/ErrorPanel';
export function TeachingPage(){
  const[subjects,setSubjects]=useState<any[]>([]);const[subjectId,setSubjectId]=useState('');const[plan,setPlan]=useState<any>(null);const[err,setErr]=useState('');
  async function init(){setErr('');try{let s:any[];try{s=(await api.examDashboard()).subjects||[]}catch{s=await api.subjects()}setSubjects(s);if(s[0])setSubjectId(s[0].id)}catch(e:any){setErr(e.message||String(e))}}
  useEffect(()=>{void init()},[]);
  useEffect(()=>{if(!subjectId)return;setPlan(null);setErr('');api.teachingPlan(subjectId).then(setPlan).catch((e:any)=>setErr(e.message||String(e)))},[subjectId]);
  return <><div className="page-head"><div><div className="eyebrow">TEACHING PLAN</div><h1>การสอน</h1><p>หน่วยการเรียน ใบงาน และทรัพยากรจากฐานข้อมูลจริง</p></div><label className="inline-select">รายวิชา<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} {s.name}</option>)}</select></label></div>{err&&<ErrorPanel message={err}/>} {plan&&<><section className="hero-panel"><div><span className="code-pill">{plan.subject?.code}</span><h2>{plan.subject?.name}</h2><p>{plan.subject?.description||'แผนการสอนรายวิชา'}</p></div><div className="big-number">{plan.units?.length||0}<small>หน่วย</small></div></section><div className="unit-grid">{(plan.units||[]).map((u:any)=><article className="unit-card" key={u.unit_no}><div className="unit-no">{String(u.unit_no).padStart(2,'0')}</div><div><div className="row-between"><h3>หน่วยที่ {u.unit_no}</h3><span className={'status-chip '+(u.unlocked?'ok':'')}>{u.unlocked?'เปิดแล้ว':'ยังไม่เปิด'}</span></div><p>{u.worksheets?.length||0} ใบงาน • {u.resources?.length||0} ทรัพยากร</p><div className="stack">{(u.worksheets||[]).map((w:any)=><div className="subrow" key={w.id}><div><b>{w.title}</b><small>{w.reference_code} • {w.mode}</small></div><span className="code-pill">{w.status}</span></div>)}</div></div></article>)}</div></>}</>
}
