import {FormEvent,useEffect,useState} from 'react';
import {api} from '../services/api';
import {supabase} from '../lib/supabase';
import {Modal} from '../components/Modal';
import {ErrorPanel} from '../components/ErrorPanel';
import type {Profile} from '../types/domain';
export function UsersPage(){
 const[items,setItems]=useState<Profile[]>([]);const[open,setOpen]=useState(false);const[err,setErr]=useState('');const[busy,setBusy]=useState(false);
 async function load(){setErr('');try{setItems(await api.users())}catch(e:any){setErr(e.message||String(e))}}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const body=Object.fromEntries(new FormData(e.currentTarget));const{data,error}=await supabase.functions.invoke('admin-create-user',{body});setBusy(false);if(error||data?.error){setErr(data?.error||error?.message||'สร้างผู้ใช้ไม่สำเร็จ');return}setOpen(false);await load()}
 return <><div className="page-head"><div><div className="eyebrow">บัญชีระบบ</div><h1>ผู้ใช้งาน</h1><p>Admin, Teacher และ Student</p></div><button className="btn primary" onClick={()=>setOpen(true)}>+ สร้างผู้ใช้</button></div>{err&&<ErrorPanel message={err} onRetry={()=>void load()}/>}<div className="data-card"><table><thead><tr><th>ชื่อ</th><th>ชื่อผู้ใช้</th><th>รหัสนักศึกษา</th><th>ห้อง</th><th>สิทธิ์</th><th>สถานะ</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.full_name||'-'}</b></td><td>{x.username||'-'}</td><td>{x.student_code||'-'}</td><td>{x.class_name||'-'}</td><td><span className="code-pill">{x.role}</span></td><td><span className={'status-chip '+(x.active?'ok':'')}>{x.active?'ใช้งาน':'ปิด'}</span></td></tr>)}</tbody></table></div>{open&&<Modal title="สร้างผู้ใช้" onClose={()=>setOpen(false)}><form onSubmit={save}><div className="form-grid"><label>ชื่อ-สกุล<input name="full_name" required/></label><label>ชื่อผู้ใช้<input name="username" required/></label><label>อีเมล<input name="email" type="email" required/></label><label>รหัสผ่านเริ่มต้น<input name="password" type="password" minLength={8} required/></label><label>รหัสนักศึกษา<input name="student_code"/></label><label>ห้องเรียน<input name="class_name"/></label><label>สิทธิ์<select name="role"><option value="user">Student/User</option><option value="teacher">Teacher</option><option value="admin">Admin</option></select></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>{busy?'กำลังสร้าง...':'สร้างผู้ใช้'}</button></div></form></Modal>}</>
}
