-- DOC-FULL-NR V17.7 Classroom Transaction Hardening
-- Applied to Production project thjscmfqunlaqxlievna on 2026-09-15.
--
-- Live contract:
-- * private.submission_idempotency: request-key receipt ledger
-- * finalize_digital_submission_v177(): idempotent Digital submit
-- * finalize_digital_submission(): preserved compatibility wrapper through hardened core
-- * save_worksheet_draft(): enrollment + ownership + hard deadline validation
-- * join_subject_with_code(): advisory-lock + idempotent enrollment/assignment
-- * submissions_work_pair_single_completion trigger: one completed channel per Digital/Paper pair
-- * admin_grade_submission_v177(): grade + submission status + audit + notification in one transaction
-- * admin_subject_gradebook(): uses finalized submission_grades score/max_score, not completion alone
-- * Paper late flow: Admin scan only, after Digital deadline, full-sheet private evidence
-- * submission_grades score integrity constraints
-- * unique scan/file idempotency indexes
-- * admin_system_health_v177(): verifies the hardened transaction contract
--
-- Production is authoritative. This release package intentionally does not contain or request
-- service_role/GitHub secrets. Use Supabase migration history for the canonical live DDL.
